services:
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
